### ISSUE TITLE
Please do some more work on little grid!

### ISSUE THREAD

**Issue by alexpetlenko** [littlegrid/www#5]
But don't code anything. Thanks. Your biggest fan, Alex

**Comment by littlegrid** [comment]
Hi Alex,

Thanks for your great support for littlegrid.  I certainly appreciate that more features could be added, although it is a balancing act - I think at the moment, littlegrid is probably "good enough" for most uses, but I'm always open to good ideas :-)

Cheers.

Regards,
Jon.
